# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 16)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 17)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 18)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 19)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 20)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 21)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 22)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 23)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 24)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 16)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 17)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 18)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 19)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 20)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 21)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 22)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 23)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 16)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 17)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 18)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 19)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 20)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 21)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 22)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 23)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 24)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 16)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 17)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 18)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 19)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 20)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 21)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 22)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 23)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 24)
