# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 16)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 17)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 18)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 19)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 20)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 21)
Document.create(file_name: 'Cold Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Paracetamol-2', user_id: 29)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 16)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 17)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 18)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 19)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 20)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 21)
Document.create(file_name: 'Pain Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. Neophem-2', user_id: 29)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 16)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 17)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 18)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 19)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 20)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 21)
Document.create(file_name: 'Stomach Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. feorite-2', user_id: 29)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 16)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 17)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 18)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 19)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 20)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 21)
Document.create(file_name: 'Dental Presecription', url: 'www.aws_link.com', category: 'Presecription', content: '1. dentalCorrect-2,  2.Floss', user_id: 29)



Document.create(file_name: 'X-Ray-1', url: 'www.aws_link.com', category: 'Medical Record', content: '1. No fracture, 2. No Head-Injury', user_id: 16)
Document.create(file_name: 'X-Ray-1', url: 'www.aws_link.com', category: 'Medical Record', content: '1. No fracture, 2. No Head-Injury', user_id: 17)
Document.create(file_name: 'X-Ray-1', url: 'www.aws_link.com', category: 'Medical Record', content: '1. No fracture, 2. No Head-Injury', user_id: 18)
Document.create(file_name: 'X-Ray-1', url: 'www.aws_link.com', category: 'Medical Record', content: '1. No fracture, 2. No Head-Injury', user_id: 19)
Document.create(file_name: 'X-Ray-1', url: 'www.aws_link.com', category: 'Medical Record', content: '1. No fracture, 2. No Head-Injury', user_id: 20)
Document.create(file_name: 'X-Ray-1', url: 'www.aws_link.com', category: 'Medical Record', content: '1. No fracture, 2. No Head-Injury', user_id: 21)
Document.create(file_name: 'X-Ray-1', url: 'www.aws_link.com', category: 'Medical Record', content: '1. No fracture, 2. No Head-Injury', user_id: 29)
Document.create(file_name: 'MRI', url: 'www.aws_link.com', category: 'Medical Record', content: '1. TB Test Pending, 2. Malaria Test Pending', user_id: 16)
Document.create(file_name: 'MRI', url: 'www.aws_link.com', category: 'Medical Record', content: '1. TB Test Pending, 2. Malaria Test Pending', user_id: 17)
Document.create(file_name: 'MRI', url: 'www.aws_link.com', category: 'Medical Record', content: '1. TB Test Pending, 2. Malaria Test Pending', user_id: 18)
Document.create(file_name: 'MRI', url: 'www.aws_link.com', category: 'Medical Record', content: '1. TB Test Pending, 2. Malaria Test Pending', user_id: 19)
Document.create(file_name: 'MRI', url: 'www.aws_link.com', category: 'Medical Record', content: '1. TB Test Pending, 2. Malaria Test Pending', user_id: 20)
Document.create(file_name: 'MRI', url: 'www.aws_link.com', category: 'Medical Record', content: '1. TB Test Pending, 2. Malaria Test Pending', user_id: 21)
Document.create(file_name: 'MRI', url: 'www.aws_link.com', category: 'Medical Record', content: '1. TB Test Pending, 2. Malaria Test Pending', user_id: 29)
Document.create(file_name: 'OPD', url: 'www.aws_link.com', category: 'Medical Record', content: '1. feorite-2', user_id: 16)
Document.create(file_name: 'OPD', url: 'www.aws_link.com', category: 'Medical Record', content: '1. feorite-2', user_id: 17)
Document.create(file_name: 'OPD', url: 'www.aws_link.com', category: 'Medical Record', content: '1. feorite-2', user_id: 18)
Document.create(file_name: 'OPD', url: 'www.aws_link.com', category: 'Medical Record', content: '1. feorite-2', user_id: 19)
Document.create(file_name: 'OPD', url: 'www.aws_link.com', category: 'Medical Record', content: '1. feorite-2', user_id: 20)
Document.create(file_name: 'OPD', url: 'www.aws_link.com', category: 'Medical Record', content: '1. feorite-2', user_id: 21)
Document.create(file_name: 'OPD', url: 'www.aws_link.com', category: 'Medical Record', content: '1. feorite-2', user_id: 29)
Document.create(file_name: 'Blood Test', url: 'www.aws_link.com', category: 'Medical Record', content: '1. dentalCorrect-2,  2.Floss', user_id: 16)
Document.create(file_name: 'Blood Test', url: 'www.aws_link.com', category: 'Medical Record', content: '1. dentalCorrect-2,  2.Floss', user_id: 17)
Document.create(file_name: 'Blood Test', url: 'www.aws_link.com', category: 'Medical Record', content: '1. dentalCorrect-2,  2.Floss', user_id: 18)
Document.create(file_name: 'Blood Test', url: 'www.aws_link.com', category: 'Medical Record', content: '1. dentalCorrect-2,  2.Floss', user_id: 19)
Document.create(file_name: 'Blood Test', url: 'www.aws_link.com', category: 'Medical Record', content: '1. dentalCorrect-2,  2.Floss', user_id: 20)
Document.create(file_name: 'Blood Test', url: 'www.aws_link.com', category: 'Medical Record', content: '1. dentalCorrect-2,  2.Floss', user_id: 21)
Document.create(file_name: 'Blood Test', url: 'www.aws_link.com', category: 'Medical Record', content: '1. dentalCorrect-2,  2.Floss', user_id: 29)